WINDOW_WIDTH = 608
WINDOW_HEIGHT = 704
CAPTION = "Triple Pac(k)"

MENU_IMG_WIDTH = 128
HEADING_FONT_SIZE_MAINSCREEN = 72
THEMES_FONT_SIZE_MAINSCREEN = 54
HOW_TO_PLAY_FONT_SIZE_MAINSCREEN = 48
DEVELOPERS = "Developed by Kalash Kankaria, Kushagra Jain and Mann Jain"

HEADING_FONT_SIZE_THEMESCREEN = 70
CHOOSE_GHOSTS_FONT_SIZE_THEMESCREEN = 54
SCORE_FONT_SIZE = 32

MAZE_ROW = 22
MAZE_COL = 19
PIXEL_SIZE = 32
IMG_PIXEL = 24
INITIAL_SCORE = 0
COIN_COLLECT_POINT = 10

#Player and Ghost Initial Positions
PLAYER_X = 9
PLAYER_Y = 16

